In [2]:
#importamos librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('ggplot')
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
# Imports needed for the script
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from IPython.display import Image as PImage
from subprocess import check_call
from PIL import Image, ImageDraw, ImageFont
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import seaborn as sns
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

In [3]:
csv_original = 'ceneval_mentor_v3.csv'
df= pd.read_csv(csv_original, encoding='latin-1', low_memory=False)

In [5]:
df.head()

Unnamed: 0  TIPO_EXA  ANO_NAC  SEXO  LENG_MA  LENG_PA  PLT_PROC  RAZ_RAPT  \
0           0    0.0077  0.90625     0      0.0      0.0    0.0355       0.0   
1           1    0.0705  1.00000     1      0.0      0.0    0.0900       1.0   
2           2    0.0705  0.90625     0      0.0      0.0    0.0900       1.0   
3           3    0.0705  1.00000     1      0.0      0.0    0.0900       1.0   
4           4    0.0705  0.84375     0      0.0      0.0    0.0900       1.0   

   RAZ_RACT  RAZ_OPT  ...  SER_TVP  SER_TABL  CUARTOS  SER_PC  SER_TV  \
0       1.0      1.0  ...      1.0       1.0     0.22     1.0     1.0   
1       0.0      0.0  ...      0.0       0.0     0.22     1.0     1.0   
2       1.0      1.0  ...      0.0       0.0     0.41     0.0     1.0   
3       1.0      1.0  ...      1.0       1.0     0.41     1.0     1.0   
4       1.0      1.0  ...      0.0       0.0     0.22     1.0     1.0   

   SER_AUTO  SER_BANO  VAC_RM  DICTAMEN  VECES_EXAM  
0       1.0       1.0     0.0         0         1.0  
1       1.0       1.0     1.0         0         1.0  
2       0.0       1.0     0.0         1         1.0  
3       0.0       1.0     1.0         1         1.0  
4       0.0       1.0     0.0         1         1.0  

[5 rows x 120 columns]

In [6]:
df.describe()

Unnamed: 0      TIPO_EXA       ANO_NAC          SEXO       LENG_MA  \
count  15613.000000  15613.000000  15613.000000  15613.000000  15613.000000   
mean    7806.000000      0.048046      0.828760      0.567156      0.032281   
std     4507.229212      0.029646      0.078357      0.495485      0.176751   
min        0.000000      0.000000      0.625000      0.000000      0.000000   
25%     3903.000000      0.020400      0.781250      0.000000      0.000000   
50%     7806.000000      0.041100      0.812500      1.000000      0.000000   
75%    11709.000000      0.065500      0.875000      1.000000      0.000000   
max    15612.000000      0.108700      1.000000      1.000000      1.000000   

            LENG_PA      PLT_PROC      RAZ_RAPT      RAZ_RACT       RAZ_OPT  \
count  15613.000000  15613.000000  15613.000000  15613.000000  15613.000000   
mean       0.031064      0.103814      0.571063      0.734196      0.890924   
std        0.173496      0.074537      0.494940      0.441775      0.311744   
min        0.000000      0.005000      0.000000      0.000000      0.000000   
25%        0.000000      0.035500      0.000000      0.000000      1.000000   
50%        0.000000      0.090000      1.000000      1.000000      1.000000   
75%        0.000000      0.175600      1.000000      1.000000      1.000000   
max        1.000000      0.220300      1.000000      1.000000      1.000000   

       ...       SER_TVP      SER_TABL       CUARTOS        SER_PC  \
count  ...  15613.000000  15613.000000  15613.000000  15613.000000   
mean   ...      0.549926      0.352399      0.274610      0.902389   
std    ...      0.497517      0.477733      0.124031      0.296797   
min    ...      0.000000      0.000000      0.020000      0.000000   
25%    ...      0.000000      0.000000      0.220000      1.000000   
50%    ...      1.000000      0.000000      0.220000      1.000000   
75%    ...      1.000000      1.000000      0.410000      1.000000   
max    ...      1.000000      1.000000      0.410000      1.000000   

             SER_TV      SER_AUTO      SER_BANO        VAC_RM      DICTAMEN  \
count  15613.000000  15613.000000  15613.000000  15613.000000  15613.000000   
mean       0.961763      0.697880      0.985717      0.722603      0.521809   
std        0.191775      0.459192      0.118659      0.447728      0.499540   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      1.000000      0.000000      0.000000   
50%        1.000000      1.000000      1.000000      1.000000      1.000000   
75%        1.000000      1.000000      1.000000      1.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

         VECES_EXAM  
count  15613.000000  
mean       0.945559  
std        0.214336  
min        0.007365  
25%        1.000000  
50%        1.000000  
75%        1.000000  
max        1.000000  

[8 rows x 120 columns]

In [8]:
print(df.groupby('DICTAMEN').size())

DICTAMEN
0    7466
1    8147
dtype: int64


In [11]:
X = np.array(df.drop(['DICTAMEN'],1))
y = np.array(df['DICTAMEN'])
X.shape

(15613, 119)

In [12]:
model = linear_model.LogisticRegression()
model.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
predictions = model.predict(X)
print(predictions)

[0 1 0 ... 0 0 0]


In [15]:
model.score(X,y)

0.6650227374623711

In [16]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)

In [18]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(msg)

Logistic Regression: 0.657326 (0.017048)


In [19]:
predictions = model.predict(X_validation)
print(accuracy_score(Y_validation, predictions))

0.6685878962536023


In [20]:
print(confusion_matrix(Y_validation, predictions))

[[ 930  570]
 [ 465 1158]]


In [21]:
print(classification_report(Y_validation, predictions))

              precision    recall  f1-score   support

           0       0.67      0.62      0.64      1500
           1       0.67      0.71      0.69      1623

    accuracy                           0.67      3123
   macro avg       0.67      0.67      0.67      3123
weighted avg       0.67      0.67      0.67      3123



In [22]:
parameters=model.coef_

In [23]:
parameters

array([[ 9.27305697e-06,  7.41094046e-01, -2.06902461e+00,
        -3.10847340e-01, -2.91190350e-01, -1.47070538e-01,
         6.81232494e+00, -2.12496724e-01, -2.38857464e-01,
        -2.80555009e-01, -2.49882580e-01,  1.99879280e-01,
         3.92218280e-01, -2.63268747e-03,  2.50193724e-01,
         2.35433294e-02, -9.17650227e-03, -2.23455125e-01,
        -3.92244506e-02, -2.68436966e-01,  1.71454657e-01,
         6.92724996e-02,  3.58245951e-01, -1.69943241e-01,
        -1.08468679e-01, -6.70189214e-02, -2.11619137e-01,
        -2.06452297e-02, -3.78697580e-02, -1.08416457e-01,
        -5.81225331e-02, -5.03725652e-01,  1.99139311e-01,
         5.87720216e-02,  2.99132959e-01,  2.02040533e-01,
        -6.92157385e-01, -6.42296196e-02, -1.72527295e-01,
         2.83607169e-01,  1.87661303e-01, -1.21581945e-01,
         6.29568239e-04, -2.20505857e-02, -2.39843989e-02,
        -5.49945202e-02,  3.85812348e-01,  4.59318301e-01,
        -1.71735085e-01, -4.61086667e-02,  2.77339826e-0

In [24]:
def sigmoid(x):
    return 1.0/(1.0 + np.exp(-x))
 
def sigmoid_derivada(x):
    return sigmoid(x)*(1.0-sigmoid(x))
 
def tanh(x):
    return np.tanh(x)
 
def tanh_derivada(x):
    return 1.0 - x**2

In [25]:
class NeuralNetwork:
 
    def __init__(self, layers, activation='tanh'):
        if activation == 'sigmoid':
            self.activation = sigmoid
            self.activation_prime = sigmoid_derivada
        elif activation == 'tanh':
            self.activation = tanh
            self.activation_prime = tanh_derivada